version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:7.10 # the primary container, where your job's commands are run

    working_directory: ~/ratify

    steps:
      - add_ssh_keys:
          fingerprints:
            - "0a:a2:37:b1:23:4a:46:d7:49:7d:b7:e6:40:6d:95:64"
      - checkout # check out the code in the project directory
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./firebase/functions/package.json" }}
          # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: cd firebase/functions && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./firebase/functions/package.json" }}

      # build!
      - run: printf "{}" > ./firebase/functions/ratify-yelp-key.json
      - run: cd firebase/functions && yarn run build && yarn run test
  android:
    working_directory: ~/ratify
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "./android/build.gradle" }}-{{ checksum  "./android/app/build.gradle" }}
      - run: sudo chmod +x ./android/gradlew
      #Download Depenencies
      - run: printf "<resources><string name=\"places_api_key\">temp</string></resources>" > ./android/app/src/main/res/values/secrets.xml
      - run: cd ./android && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "./android/build.gradle" }}-{{ checksum  "./android/app/build.gradle" }}
      # Run Build
      - run: cd ./android && ./gradlew :app:bundleDebug
      - store_artifacts:
          path: ./android/app/build/reports
          destination: reports
      - store_test_results:
          path: ./android/app/build/test-results
workflows:
  version: 2
  build_all:
    jobs:
      - build
      - android



