export const errorCodes = {
  'ok': 'OK',
  'cancelled': 'CANCELLED',
  'unknown': 'UNKNOWN',
  'invalid-argument': 'INVALID_ARGUMENT',
  'deadline-exceeded': 'DEADLINE_EXCEEDED',
  'not-found': 'NOT_FOUND',
  'already-exists': 'ALREADY_EXISTS',
  'permission-denied': 'PERMISSION_DENIED',
  'unauthenticated': 'UNAUTHENTICATED',
  'resource-exhausted': 'RESOURCE_EXHAUSTED',
  'failed-precondition': 'FAILED_PRECONDITION',
  'aborted': 'ABORTED',
  'out-of-range': 'OUT_OF_RANGE',
  'unimplemented': 'UNIMPLEMENTED',
  'internal': 'INTERNAL',
  'unavailable': 'UNAVAILABLE',
  'data-loss': 'DATA_LOSS',
};